Recommender/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Recommender.Models;
using Recommender.Models.ViewModels;
using Recommender.Infrastructure;

namespace Recommender.Controllers
{
    public class MovieController : Controller
    {
        private IMovieRepository    movieRep;
        private IGenreRepository    genreRep;
        private IUserRateRepository userRateRep;

        public MovieController(IMovieRepository movieRep, IGenreRepository genreRep, IUserRateRepository userRateRep)
        {
            this.movieRep = movieRep;
            this.genreRep = genreRep;
            this.userRateRep = userRateRep;
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<UserRate> userRates = await User.GetUserRatesAsync(userRateRep);

            var baseRequest = movieRep.Movies
                                    //.Where(m => !userRates.Select(ur => ur.TitleId).Contains(m.Id))
                                    .Where(m => m.ReleaseDate.HasValue && m.ReleaseDate.Value.Year > (DateTime.Now.Year - 2))
                                    .Where(m => m.VoteCount > 100);

            if (userRates != null)
            {
                baseRequest = baseRequest.Where(m => !userRates.Select(ur => ur.TitleId).Contains(m.Id));
            }

            var moviesOnCinema = await baseRequest
                                    .OrderByDescending(m => m.ReleaseDate)
                                    .Take(5)
                                    .ToListAsync();

            var recommendedMovies = await baseRequest
                                    .OrderByDescending(m => m.VoteAverage)
                                    .Take(10)
                                    .ToListAsync();

            recommendedMovies.ForEach(m => m.VoteAverage = 8);
            recommendedMovies[0].VoteAverage = recommendedMovies[1].VoteAverage = recommendedMovies[2].VoteAverage = 10;
            recommendedMovies[3].VoteAverage = recommendedMovies[4].VoteAverage = recommendedMovies[5].VoteAverage = 9.6;

            var interestingMovies = await baseRequest
                                    .Where(m => !recommendedMovies.Select(mv => mv.Id).Contains(m.Id))
                                    .Where(m => m.VoteAverage >= 7)
                                    .OrderByDescending(m => m.Popularity)
                                    .Take(10)
                                    .ToListAsync();

            var model = new MovieIndex
            {
                MoviesOnCinema = moviesOnCinema.GetUserMovies(userRates),
                RecommendedMovies = recommendedMovies.GetUserMovies(userRates),
                InterestingMovies = interestingMovies.GetUserMovies(userRates)
            };

            return View(model);
        }

        public async Task<IActionResult> List() => 
            View(await movieRep.Movies
                             .Where(m => m.PosterPath != null && m.ReleaseDate.HasValue && m.ReleaseDate.Value.Year == DateTime.Now.Year)
                             .OrderByDescending(m => m.Popularity)
                             .Take(10)
                             .ToListAsync());

        public async Task<IActionResult> Title(int titleId)
        {
            var movie = await movieRep.Movies.FirstOrDefaultAsync(m => m.Id == titleId);
            UserRate userRate = await userRateRep.GetUserRateByUserAndTitleAsync(User.GetUserId(), movie.Id);
            if (movie == null) { return NotFound(); }
            return View(new UserMovie(movie, userRate?.Score ?? 0));
        }

        public async Task<IActionResult> Genre(int genreId, int page = 1)
        {
            var genre = await genreRep.Genres.FirstOrDefaultAsync(g => g.Id == genreId);

            if (genre == null) { return NotFound(); }

            var count = await movieRep.Movies.Where(m => m.Genres.Contains(genreId)).CountAsync();

            var pagingInfo = new PagingInfo(count, 24, page);

            var movies = await movieRep.GetMoviesByGenre(genreId)
                .OrderByDescending(m => m.Popularity)
                .Skip((page - 1) * pagingInfo.ItemsPerPage)
                .Take(pagingInfo.ItemsPerPage)
                .ToListAsync();

            if (movies == null) { movies = new List<Movie>(); }

            IEnumerable<UserRate> userRates = await User.GetUserRatesAsync(userRateRep);

            return View(new MovieOfGenreViewModel {
                Genre = genre,
                UserMovies = movies.GetUserMovies(userRates),
                PagingInfo = pagingInfo
            });
        }

        public async Task<IActionResult> Search(string query, int page = 1)
        {
            var moviesByQuery = movieRep.Movies.Where(m => m.Title.Contains(query) || m.OriginalTitle.Contains(query));

            var count = await moviesByQuery.CountAsync();

            var pagingInfo = new PagingInfo(count, 24, page);

            var movies = await moviesByQuery.
                OrderByDescending(m => m.Popularity)
                .Skip((page - 1) * pagingInfo.ItemsPerPage)
                .Take(pagingInfo.ItemsPerPage)
                .ToListAsync();

            if (movies == null) { movies = new List<Movie>(); }

            IEnumerable<UserRate> userRates = await User.GetUserRatesAsync(userRateRep);

            return View(new SearchResult
            {
                Query = query,
                Results = movies,
                PagingInfo = pagingInfo
            });
        }

        public async Task<IActionResult> Test() => View(await movieRep.Movies
                             .Where(m => m.PosterPath != null && m.ReleaseDate.HasValue && m.ReleaseDate.Value.Year == DateTime.Now.Year)
                             .OrderByDescending(m => m.Popularity)
                             .Take(10)
                             .ToListAsync());
    }
}

Recommender/Views/Shared/CountryList.cshtml
<ul class="dropdown-menu multi-column columns-3">
    <li>
        <div class="col-sm-4">
            <ul class="multi-column-dropdown">
                <li><a href="genres.html">Asia</a></li>
                <li><a href="genres.html">France</a></li>
                <li><a href="genres.html">Taiwan</a></li>
                <li><a href="genres.html">United States</a></li>
            </ul>
        </div>
        <div class="col-sm-4">
            <ul class="multi-column-dropdown">
                <li><a href="genres.html">China</a></li>
                <li><a href="genres.html">HongCong</a></li>
                <li><a href="genres.html">Japan</a></li>
                <li><a href="genres.html">Thailand</a></li>
            </ul>
        </div>
        <div class="col-sm-4">
            <ul class="multi-column-dropdown">
                <li><a href="genres.html">Euro</a></li>
                <li><a href="genres.html">India</a></li>
                <li><a href="genres.html">Korea</a></li>
                <li><a href="genres.html">United Kingdom</a></li>
            </ul>
        </div>
        <div class="clearfix"></div>
    </li>
</ul>

Recommender/Views/Shared/GenreLinkList.cshtml
@model IEnumerable<int>
@inject IGenreRepository Rep

<h4>
@foreach (var genre in Rep.Genres.Where(g => Model.Contains(g.Id)).ToList())
{
    <a asp-action="Genre" asp-controller="Movie" asp-route-genreId="@genre.Id" 
       target="_blank" 
       class="label label-default" 
       style="display:inline-block; margin-bottom:0.2em; margin-top:0.2em">
        @genre.RuName
    </a>  
}
</h4>

Recommender/Views/Shared/GenreList.cshtml
@using Recommender.Infrastructure;
@inject IGenreRepository Rep

<ul class="dropdown-menu multi-column columns-3">
    <li>
        @foreach (var list in Rep.Genres.Split(3))
        {
            <div class="col-sm-4">
                <ul class="multi-column-dropdown">
                    @foreach (var genre in list)
                    {
                        <li><a asp-controller="Movie" asp-action="Genre" asp-route-genreId="@genre.Id">@genre.RuName</a></li>
                    }
                </ul>
            </div>
        }
        <div class="clearfix"></div>
    </li>
</ul>

Recommender/Views/Shared/LoginModalForm.cshtml
@model LoginModel

<form asp-controller="Account" asp-action="Login" asp-anti-forgery="true" method="post">
    <input type="hidden" asp-for="ReturnUrl" value="@(ViewContext.HttpContext.Request.Path + @ViewContext.HttpContext.Request.QueryString)" />
    <input type="text" asp-for="UserName" placeholder="Логин" required="" />
    <span asp-validation-for="UserName" />
    <input asp-for="Password" placeholder="Пароль" required="" />
    <span asp-validation-for="Password" />
    <input type="submit" value="Войти" />
</form>

Recommender/Views/Shared/MovieBlock.cshtml
@model UserMovie

<div class="col-md-2 w3l-movie-gride-agile">
    <a asp-action="Title" asp-controller="Movie" asp-route-titleId="@Model.Movie.Id" class="hvr-shutter-out-horizontal">
        <img src="http://image.tmdb.org/t/p/w185/@Model.Movie.PosterPath" title="@Model.Movie.Title" class="img-responsive" alt="@Model.Movie.Title" />
        <div class="w3l-action-icon"><i class="fa fa-play-circle" aria-hidden="true"></i></div>
    </a>
    <div class="mid-1">
        <div class="w3l-movie-text" style="min-height:60px">
            <h6><a asp-action="Title" asp-controller="Movie" asp-route-titleId="@Model.Movie.Id">@Model.Movie.Title</a></h6>
        </div>
        <div class="mid-2">

            <p>@Model.Movie.ReleaseDate?.Year</p>
            <stars-block title-id="@Model.Movie.Id" 
                         score="@{(Model.NotRated) ? (int)Math.Round(Model.Movie.VoteAverage) : Model.UserScore}" 
                         default="@Model.NotRated" 
                         rate-action="Rate" rate-controller="UserRate">
            </stars-block>
            <div class="clearfix"></div>
        </div>
    </div>
    @if (Math.Abs((Model.Movie.ReleaseDate - DateTime.Now).Value.TotalDays) < 30)
    {
        <div class="ribben two">
            <p>NEW!</p>
        </div>
    }
</div>

Recommender/Views/Shared/MovieInCarouselBlock.cshtml
@model UserMovie

<div class="item">
    <div class="w3l-movie-gride-agile w3l-movie-gride-agile1">
        <a asp-action="Title" asp-controller="Movie" asp-route-titleId="@Model.Movie.Id" class="hvr-shutter-out-horizontal">
            <img src="http://image.tmdb.org/t/p/w185/@Model.Movie.PosterPath" title="@Model.Movie.Title" class="img-responsive" alt="@Model.Movie.Title" />
            <div class="w3l-action-icon"><i class="fa fa-play-circle" aria-hidden="true"></i></div>
        </a>
        <div class="mid-1 agileits_w3layouts_mid_1_home">
            <div class="w3l-movie-text" style="min-height:37px">
                <h6><a asp-action="Title" asp-controller="Movie" asp-route-titleId="@Model.Movie.Id">@Model.Movie.Title</a></h6>
            </div>
            <div class="mid-2 agile_mid_2_home">
                <p>@Model.Movie.ReleaseDate?.Year</p>
                <stars-block title-id="@Model.Movie.Id"
                             score="@{(Model.NotRated) ? (int)Math.Round(Model.Movie.VoteAverage) : Model.UserScore}"
                             default="@Model.NotRated"
                             rate-action="Rate" rate-controller="UserRate">
                </stars-block>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>

Recommender/Views/Shared/RegisterModalForm.cshtml
@model RegisterModel

<form asp-controller="Account" asp-action="Register" asp-anti-forgery="true" method="post">
    <div asp-validation-summary="All"></div>
    <input type="hidden" asp-for="ReturnUrl" value="@(ViewContext.HttpContext.Request.Path + @ViewContext.HttpContext.Request.QueryString)" />
    <input type="text" asp-for="UserName" placeholder="Введите логин" required="" />
    <span asp-validation-for="UserName" />
    <input type="text" asp-for="Email" placeholder="Введите Email" required="" />
    <span asp-validation-for="Email" />
    <input asp-for="Password" placeholder="Введите пароль" required="" />
    <span asp-validation-for="Password" />
    <input asp-for="ConfirmPassword" placeholder="Повторите пароль" required="" />
    <span asp-validation-for="ConfirmPassword" />
    <input type="submit" value="Регистрация" />
</form>

Recommender/Views/Shared/StarsBlock.cshtml
@model double /* movie.VoteAvarage */
@inject IUserRateRepository Rep

<div class="block-stars" data-score="0" data-user_set="false">
    <ul class="w3l-ratings">
        @for (int i = 0; i < Math.Truncate(Model / 2); i++)
        {
            <li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>
        }
        @if (Model % 2 >= 0.5)
        {
            <li><a href="#"><i class="fa fa-star-half-o" aria-hidden="true"></i></a></li>
        }
        @for (int i = 0; i < Math.Truncate((10 - Model) / 2); i++)
        {
            <li><a href="#"><i class="fa fa-star-o" aria-hidden="true"></i></a></li>
        }
    </ul>
</div>

Recommender/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Recommender | @ViewData["Title"]</title>
    <!-- for-mobile-apps -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <!-- //for-mobile-apps -->
    <link rel="stylesheet" href="~/css/bootstrap.css" type="text/css" media="all" />
    <link rel="stylesheet" href="~/lib/normalize-css/normalize.css" type="text/css" media="all" />
    <!--<link rel="stylesheet" asp-href-include="lib/bootstrap/dist/css/*.min.css" type="text/css" media="all" />-->
    <link rel="stylesheet" href="~/css/style.css" type="text/css" media="all" />
    <link rel="stylesheet" href="~/css/contactstyle.css" type="text/css" media="all" />
    <link rel="stylesheet" href="~/css/faqstyle.css" type="text/css" media="all" />
    <link rel='stylesheet' href="~/css/single.css" type='text/css' />
    <link rel="stylesheet" href="~/css/medile.css" type='text/css' />
    <!-- banner-slider -->
    <link href="~/css/jquery.slidey.min.css" rel="stylesheet">
    <!-- //banner-slider -->
    <!-- pop-up -->
    <link href="~/css/popuo-box.css" rel="stylesheet" type="text/css" media="all" />
    <!-- //pop-up -->
    <!-- font-awesome icons -->
    <link rel="stylesheet" href="~/css/font-awesome.min.css" />
    <!-- //font-awesome icons -->
    <!-- js -->
    <script type="text/javascript" src="~/js/jquery-2.1.4.min.js"></script>
    <!-- //js -->
    <!-- banner-bottom-plugin -->
    <link href="~/css/owl.carousel.css" rel="stylesheet" type="text/css" media="all">
    <script src="~/js/owl.carousel.js"></script>
    <script>
        $(document).ready(function () {
            $("#owl-demo, #owl-demo-2").owlCarousel({

                autoPlay: 3000, //Set AutoPlay to 3 seconds

                items: 5,
                itemsDesktop: [640, 4],
                itemsDesktopSmall: [414, 3]

            });

        });
    </script>
    <!-- //banner-bottom-plugin -->
    <!-- <link href='//fonts.googleapis.com/css?family=Roboto+Condensed:400,700italic,700,400italic,300italic,300' rel='stylesheet' type='text/css'> -->
    <link href="http://fonts.googleapis.com/css?family=Roboto+Condensed:300,300i,400,400i,700,700i&amp;subset=cyrillic" rel="stylesheet" type='text/css'>
    <!-- start-smoth-scrolling -->
    <script type="text/javascript" src="~/js/move-top.js"></script>
    <script type="text/javascript" src="~/js/easing.js"></script>
    <script type="text/javascript">
        jQuery(document).ready(function ($) {
            $(".scroll").click(function (event) {
                event.preventDefault();
                $('html,body').animate({ scrollTop: $(this.hash).offset().top }, 1000);
            });
        });
    </script>
    <!-- start-smoth-scrolling -->
</head>

<body>
    <!-- header -->
    <div class="header">
        <div class="container">
            <div class="w3layouts_logo">
                <a asp-controller="Movie" asp-action="Index"><h1>Recom<span>mender</span></h1></a>
            </div>
            <div class="w3_search">
                <form asp-action="Search" asp-controller="Movie" method="get">
                    <input type="text" name="query" placeholder="Поиск..." required="">
                    <input type="submit" value="Поиск">
                </form>
            </div>
            <div class="w3l_sign_in_register">
                <ul>
                    @if (User.Identity.IsAuthenticated)
                    {

                        <li><a asp-controller="User" asp-action="Index" asp-route-userName="@User.Identity.Name">@User.Identity.Name</a></li>
                        <li><a asp-controller="Account" asp-action="Logout">Выход</a></li>
                    }
                    else
                    {
                        <li><a href="#" data-toggle="modal" data-target="#myModal">Login</a></li>
                    }
                </ul>
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
    <!-- //header -->
    <!-- bootstrap-pop-up -->
    <div class="modal video-modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    Вход/Регистрация
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                </div>
                <section>
                    <div class="modal-body">
                        <div class="w3_login_module">
                            <div class="module form-module">
                                <div class="toggle">
                                    <i class="fa fa-times fa-pencil"></i>
                                    <div class="tooltip">Регистрация</div>
                                </div>
                                <div class="form">
                                    <h3>Вход</h3>
                                    @Html.Partial("LoginModalForm", new LoginModel())
                                </div>
                                <div class="form">
                                    <h3>Регистрация</h3>
                                    @Html.Partial("RegisterModalForm", new RegisterModel())
                                </div>
                                <div class="cta"><a href="#">Забыли пароль?</a></div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
    <script>
        $('.toggle').click(function () {
            // Switches the Icon
            $(this).children('i').toggleClass('fa-pencil');
            // Switches the forms
            $('.form').animate({
                height: "toggle",
                'padding-top': 'toggle',
                'padding-bottom': 'toggle',
                opacity: "toggle"
            }, "slow");
        });
    </script>
    <!-- //bootstrap-pop-up -->
    <!-- nav -->
    <div class="movies_nav">
        <div class="container">
            <nav class="navbar navbar-default">
                <div class="navbar-header navbar-left">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
                    <nav>
                        <ul class="nav navbar-nav">
                            <li class=""><a asp-controller="Movie" asp-action="Index">Главная</a></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Жанры <b class="caret"></b></a>
                                @Html.Partial("GenreList")
                            </li>
                            <!--<li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Страны <b class="caret"></b></a>
                                @Html.Partial("CountryList")
                            </li>-->
                        </ul>
                    </nav>
                </div>
            </nav>
        </div>
    </div>
    <!-- //nav -->
    @RenderBody();
    <!-- social buttons-->
    <!--
    <div class="general_social_icons">
        <nav class="social">
            <ul>
                <li class="w3_twitter"><a href="#">Twitter <i class="fa fa-twitter"></i></a></li>
                <li class="w3_facebook"><a href="#">Facebook <i class="fa fa-facebook"></i></a></li>
                <li class="w3_dribbble"><a href="#">Dribbble <i class="fa fa-dribbble"></i></a></li>
                <li class="w3_g_plus"><a href="#">Google+ <i class="fa fa-google-plus"></i></a></li>
            </ul>
        </nav>
    </div>
    -->
    <!-- //social buttons -->
    <!-- footer -->
    <div class="footer">
        <div class="container">
            <div class="col-md-5 w3ls_footer_grid1_left">
                <p>&copy; 2018 Recommender</p>
            </div>
            <div class="col-md-7 w3ls_footer_grid1_right">
                <p style="color:#999">Design by <a href="http://w3layouts.com/">W3layouts</a></p>
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
    <!-- //footer -->
    <!-- Bootstrap Core JavaScript -->
    <script src="~/js/bootstrap.min.js"></script>
    <script>
        $(document).ready(function () {
            $(".dropdown").hover(
                function () {
                    $('.dropdown-menu', this).stop(true, true).slideDown("fast");
                    $(this).toggleClass('open');
                },
                function () {
                    $('.dropdown-menu', this).stop(true, true).slideUp("fast");
                    $(this).toggleClass('open');
                }
            );
        });
    </script>
    <!-- //Bootstrap Core JavaScript -->
    <script type="text/javascript" src="~/js/starsBlock.js"></script>
    <!-- here stars scrolling icon -->
    <script type="text/javascript">
        $(document).ready(function () {
            /*
                var defaults = {
                containerID: 'toTop', // fading element id
                containerHoverID: 'toTopHover', // fading element hover id
                scrollSpeed: 1200,
                easingType: 'linear'
                };
            */

            $().UItoTop({ easingType: 'easeOutQuart' });

        });
    </script>
    <!-- //here ends scrolling icon -->
</body>
</html>